### ISSUE TITLE
[REQ] and [OPINION] README

### ISSUE THREAD

**Issue by Aldanium** [rakion99/IceMeme#29]
Er.. It's not as bad as you would think.. However first of all.. This includes LOADS of errors. To fix you must add all the LUA.HPP, LUA.H ETC. Files. But then you keep getting LINKER errors and such. I'm actually confused by this. How do I fix it? I'm not saying to use but to keep in mind in general as well. Either way. Good job I guess?

**Comment by rakion99** [comment]
rly? you didnt read the readme..... even with big letters come on....
![image](https://user-images.githubusercontent.com/1360084/35524696-f1ed9bcc-04e7-11e8-814c-1ca0be81ff26.png)
