### ISSUE TITLE
Dll Source Code is missing

### ISSUE THREAD

**Issue by EspritYT** [rakion99/IceMeme#39]
Hi,

In The Source Code, There is the IceMemeUI but there isn't  the souce code of IceMeme (C++)

Sorry for my english but I'm French

**Comment by rakion99** [comment]
no is not missing only removed, since no one was learning(or at least trying to learn) on how to update or at least adding stuff or making it more stable and only download, change name and steal without adding credits so there no point in keeping it up to date and open source

**Comment by EspritYT** [comment]
But now it's not a open source

**Comment by rakion99** [comment]
![image](https://user-images.githubusercontent.com/1360084/36171085-f0a829b8-10c6-11e8-810f-6d273f061d53.png)
still open source...... anyway you probably don't know c++ and/or c# so no need for a source that you don't understand
