### ISSUE TITLE
Cannot open include file "lua.hpp"

### ISSUE THREAD

**Issue by Quorz** [rakion99/IceMeme#42]
so i have the C++, i have everything but when im going to built it says this, here is a screenshot of the error: https://gyazo.com/1fe0756dada0d44005b3b59be349d92d
it is at the line 10 in the Main.h file

**Comment by AntiKDev** [comment]
You just need add directories of lua include in your properties of c++ project.

**Comment by Quorz** [comment]
hi, i appreciate your help, i add it but the problem still, any other suggestion?

**Comment by rakion99** [comment]
to fix it you need to include lua source or lua lib and includes

**Comment by Quorz** [comment]
now it works, thanks!
