### ISSUE TITLE
Update Crashing Problems

### ISSUE THREAD

**Issue by Aldanium** [rakion99/IceMeme#43]
Yeah. So I have updated this shit and whatnot. Anyways. I updated and it still crashes. I can't tell if it's the contextlevel anymore because whenever I remove the `*(DWORD*)contextlevel = 6;` itself. It doesn't crash when Injected. But when I run a simple script such as print() It does crash. If I add that. Next to the lua state. It crashes on injection. I'm pretty sure I've updated this as much as I can..

My addresses are

`DWORD getfield = aslr_bypass(0x71FA10);
DWORD settop = aslr_bypass(0x71AA10);
DWORD pushstring = aslr_bypass(0x720D90);
DWORD pushvalue = aslr_bypass(0x71F660);
DWORD setfield = aslr_bypass(0x721710);
DWORD pushnumber = aslr_bypass(0x720D00);
DWORD scriptcontextvftable = aslr_bypass(0xFF9508);
DWORD getmetatable = aslr_bypass(0x721530);
DWORD pcall = aslr_bypass(0x7207D0);
DWORD rawrjz = aslr_bypass(0x718FE7);
DWORD pushboolean = aslr_bypass(0x7220D0);
DWORD contextlevel = aslr_bypass(0x58CA16);
DWORD pushnil = aslr_bypass(0x722C50);`

LUA STATE IS = 	luaState = v41 + 56 * v49 + 164 - *(DWORD *)(v41 + 56 * v49 + 164);
	*(DWORD*)contextlevel = 6;

Any help would be appreciated. I'm not trying to skid instead learning how to update without any problems.

**Comment by rakion99** [comment]
if crash after command too is ur luaState and sometimes is one of you address

**Comment by Aldanium** [comment]
Er. Okay.. Luastate? I used the definition on V50. I don't see how? Mind helping on that on Discord? Please.
