### ISSUE TITLE
Injection failed

### ISSUE THREAD

**Issue by Quorz** [rakion99/IceMeme#44]
i have the dll in the folder, the same that i named in functions, but when i try to inject it says injection failed, i have also the addresses updated.
screenshot: https://gyazo.com/16f137348020f5353ec129f1eb84ec6b

**Comment by rakion99** [comment]
try another injector like extreme injector and see if throw a null injection or other error

**Comment by Doller3795** [comment]
so compress ur file by .zip and open up and inject it again it should inject. or try to use dll injector or something u can inject

**Comment by SuperJLoew** [comment]
I have the same question, i have the dll in the folder, the same that i named in functions, but when i try to inject it says injection failed, i have also the addresses updated.
screenshot: https://gyazo.com/16f137348020f5353ec129f1eb84ec6b
