### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EspritYT** [rakion99/IceMeme#46]
Can you share the first version you have released of IceMeme (the dll)

**Comment by gabe56f** [comment]
I agree...

**Comment by rakion99** [comment]
the dll is in Relase tab in my github, there only UI source for now
https://github.com/rakion99/IceSource/releases/latest

**Comment by Mr817277377372** [comment]
I have no fricking Idea why I get these gmails .-.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
