### ISSUE TITLE
Dont Get The Dll

### ISSUE THREAD

**Issue by epicmatthew21** [rakion99/IceMeme#47]
Its On Release And On X86 But In The Folder I Dont Get The DLL

**Comment by Angelbooy** [comment]
Make it.

**Comment by epicmatthew21** [comment]
how

**Comment by rakion99** [comment]
the dll is in relases in github..... there no more source for dll so make your own by learning c++
or download the dll in releases https://github.com/rakion99/IceMeme/releases
