### ISSUE TITLE
A few questions.

### ISSUE THREAD

**Issue by SuperJLoew** [rakion99/IceMeme#55]
1.what is made up of an lvl 7  
2.i added a button to your thing and now when i try opening it, it doesn't open, is it cause i need a new dll to open that im guessing it is and if so i can fix that in 2 seconds.
thx.

**Comment by lowlyzapped** [comment]
Hey SuperJLoew Do you have discord if so add me. lowlyzapped#6640 I maybe able to answer questions as well.

**Comment by SuperJLoew** [comment]
ok thx

**Comment by SomeExpert101** [comment]
If you want to open your exe without the box message popping up, Go to program.cs and delete:
                if (!File.Exists("./IceMeme.dll"))
                {
                    MessageBox.Show("IceMeme.dll not found", "ERROR", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    Environment.Exit(0);
                }
