### ISSUE TITLE
Problem Opening IceMeme

### ISSUE THREAD

**Issue by HurricaneIrma** [rakion99/IceMeme#56]
In the Winrar folder when I try to open IceMemeUI.exe it gives me the error message
    Cannot execute "C:\Users\Owner\AppData\Local\Temp\Rar$EXa10924.1680\IceMemeRelease\IceMemeUI.exe"
What can I do about it?

**Comment by rakion99** [comment]
try turning off your antivirus since they are paranoid because the injector, the named pipes and other stuff

**Comment by Fogdoggy** [comment]
How Do i change The dll name?
