### ISSUE TITLE
stop spoonfeeding

### ISSUE THREAD

**Issue by andrew2561** [rakion99/IceMeme#65]
yes

**Comment by rakion99** [comment]
ok i'll stop updating icememe for $25

**Comment by Doller3795** [comment]
rakion just wants money XD

**Comment by andrew2561** [comment]
is pepsi ok

**Comment by rakion99** [comment]
send me money now 🙃 or i'll update soon 😈

**Comment by PaziHD** [comment]
did roblox hit that yeet on icememe bc it wont inject anymore
