### ISSUE TITLE
Hey uh question

### ISSUE THREAD

**Issue by thebestname21422** [rakion99/IceMeme#66]
What does this mean lmao "now when you click ACCEPT your information will be public in the discord so anyone there can see them" What type of information we talking here

**Comment by rakion99** [comment]
![image](https://user-images.githubusercontent.com/1360084/42975010-830f58b6-8b7f-11e8-93c0-9452eaf2f553.png)

**Comment by thebestname21422** [comment]
That is crazy, can you provide a logical reason for this.

**Comment by rakion99** [comment]
because i want 😃 😋 this is logical to me

**Comment by SPIKEISBACK** [comment]
Seems legit
