### ISSUE TITLE
Work ? 

### ISSUE THREAD

**Issue by NathanDevJ** [rakion99/IceMeme#68]
it does not work 
![capture](https://user-images.githubusercontent.com/20014722/50305634-b7b05100-0493-11e9-915e-4f9b6f3cfc1d.PNG)

**Comment by DONTINJECTIT** [comment]
DO NOT INJECT IT IS WHAT I CAN TELL YOU THE PROGRAM IS A LIE IT WILL GIVE YOU A TROGAN VIRUS IT IS THE WORST TYPE ONCE YOU HAVE INSTALLED IT THERE IS NO GOING BACK THE VIRUS WILL SPREAD AND SPREAD THEN YOUR PC WILL SLOW DOWN HEAT UP AND WHEN YOU TRY TO START IT UP IT WONT WORK SO WHILE YOU STILL CAN PLEASE DO SO AND REMOVE VISUAL STUDIOS AND GET YOUR PROTECTION BACK UP SO THEN YOU CAN REMOVE IT AS QUICK AS POSSIBLE. DO IT FAST BEFORE HE REMOVES MY COMMENT PLEASE.
